/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ekspertsystemowliczbowych;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 * Okno pomocy.
 * @author Bartosz Myrcha
 */
public class Pomoc extends javax.swing.JFrame {

    /**
     * Główny konstruktor klasy - ukrycie obramowania okna oraz inicjalizacja komponentów okna.
     */
    public Pomoc() {
        this.setUndecorated(true); //Ukryj obramowanie okna
        initComponents(); //inicjalizuj komponenty
        Prev.setVisible(false);
    }
    int nr_strony=1;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        Pomoc = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        Prev = new javax.swing.JLabel();
        Next = new javax.swing.JLabel();
        Grafika = new javax.swing.JLabel();
        Tlo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 768));
        getContentPane().setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(1024, 768));
        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 768));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 768));
        jPanel1.setLayout(null);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        jPanel1.add(Logo);
        Logo.setBounds(108, 0, 809, 68);

        Pomoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pomoc.png"))); // NOI18N
        jPanel1.add(Pomoc);
        Pomoc.setBounds(430, 80, 169, 68);

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ExitMousePressed(evt);
            }
        });
        jPanel1.add(Exit);
        Exit.setBounds(980, 0, 45, 29);

        Prev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/wstecz.png"))); // NOI18N
        Prev.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Prev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PrevMousePressed(evt);
            }
        });
        jPanel1.add(Prev);
        Prev.setBounds(10, 421, 82, 64);

        Next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nastepne.png"))); // NOI18N
        Next.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NextMousePressed(evt);
            }
        });
        jPanel1.add(Next);
        Next.setBounds(920, 423, 82, 64);

        Grafika.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pomoc1.png"))); // NOI18N
        jPanel1.add(Grafika);
        Grafika.setBounds(108, 180, 800, 550);

        Tlo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tlo.jpg"))); // NOI18N
        jPanel1.add(Tlo);
        Tlo.setBounds(0, 0, 1024, 768);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1024, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Wykrycie wciśnięcia przycisku przechodzącego do menu - zamykanie bieżącego okna i otwieranie okna menu głównego gry.
     * @param evt zdarzenie myszy
     */
    private void ExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMousePressed
        this.dispose(); //zamknij bieżące okno
        MenuGlowne menu = new MenuGlowne(); //stwórz nowy obiekt klasy MenuGlowne o nazwie menu
        menu.setExtendedState(JFrame.MAXIMIZED_BOTH); //maksymalizuj okno menu
        menu.setVisible(true); //ustaw okno menu jako widoczne
    }//GEN-LAST:event_ExitMousePressed

   /**
     * Wyświetlenie poprzedniego obrazu pomocy.
     * @param evt zdarzenie myszy
     */
    private void PrevMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrevMousePressed
        if(nr_strony>1)
        {
            nr_strony--;
            Grafika.setIcon(new ImageIcon(getClass().getResource("/img/pomoc"+nr_strony+".png")));
            Next.setVisible(true);
        }
        if(nr_strony==1) Prev.setVisible(false);
    }//GEN-LAST:event_PrevMousePressed
    /**
     * Wyświetlenie kolejnego obrazu pomocy.
     * @param evt zdarzenie myszy
     */
    private void NextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextMousePressed
        if(nr_strony<5)
        {
            nr_strony++;
            Grafika.setIcon(new ImageIcon(getClass().getResource("/img/pomoc"+nr_strony+".png")));
            Prev.setVisible(true);
        }
        if(nr_strony==5) Next.setVisible(false);
    }//GEN-LAST:event_NextMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pomoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pomoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pomoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pomoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pomoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel Grafika;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Next;
    private javax.swing.JLabel Pomoc;
    private javax.swing.JLabel Prev;
    private javax.swing.JLabel Tlo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
